imports:
- path: qwiklabs.jinja

resources:
- name: qwiklabs
  type: qwiklabs.jinja
  properties:
    zone: us-central1-a
    region: us-west1
    userName: googlestudent
    userPassword: googlestudent
    sshPubKey: A123412341234
    qwiklabsUuid: ql-1e433efb3de8
